# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('ParentID', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('UserName', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('password', models.IntegerField(blank=True, default=None, null=True)),
                ('ParentCode', models.IntegerField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('studentCode', models.IntegerField(default=None)),
                ('SID', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
