# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_page_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='ParentCode',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='UserName',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='password',
        ),
        migrations.AddField(
            model_name='parent',
            name='phone',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='SID',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
