# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0002_auto_20180117_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
