# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0003_auto_20180117_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='home_page_app.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='GradeLevel',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
