# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0005_auto_20180122_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='fName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
