# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0007_parent_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aname', models.CharField(blank=True, max_length=30, null=True)),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_points_possible', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('score', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=6, null=True)),
                ('sections', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('assignments', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='home_page_app.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('TeacherId', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='GradeLevel',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacherFK',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='home_page_app.teacher'),
        ),
        migrations.AddField(
            model_name='clas',
            name='subjectsFK',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='home_page_app.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='GradeLevelFK',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='home_page_app.clas'),
        ),
    ]
