# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0008_auto_20180126_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
