# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0010_auto_20180126_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacherFK',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='home_page_app.subject'),
        ),
    ]
