# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0011_auto_20180126_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clas',
            name='subjectsFK',
        ),
        migrations.AddField(
            model_name='clas',
            name='subjectsFK',
            field=models.ManyToManyField(to='home_page_app.subject'),
        ),
    ]
