# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0012_auto_20180126_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='subjectName',
        ),
    ]
