# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0014_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
