# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0015_auto_20180127_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='TeacherId',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
